import 'package:road_man_project/features/_08_job_view/data/model/suggested_jobs_item_model.dart';

import '../../../../../../generated/assets.dart';
import '../../../../data/model/recent_jobs_card_item_model.dart';

class JobViewConstList {
  static const List<SuggestedJobsItemModel> suggestedJobsItemModelList = [
    SuggestedJobsItemModel(
      trackLocationImage: Assets.jobGoogleIcon,
      trackLocationTitle: 'Content Marketing',
      trackLocationSubtitle: 'Google | Cairo | Egypt',
      price: '\$42- \$48k',
      subscriptionType: ' /monthly',
      workingTimeSectionTitle1: 'Part_Time',
      workingTimeSectionTitle2: 'Advanced Level',
    ),
    SuggestedJobsItemModel(
      trackLocationImage: Assets.jobGoogleIcon,
      trackLocationTitle: 'Flutter Developer',
      trackLocationSubtitle: 'Google | Cairo | Egypt',
      price: '\$1000- \$1500k',
      subscriptionType: ' /monthly',
      workingTimeSectionTitle1: 'Full_Time',
      workingTimeSectionTitle2: 'Advanced Level',
    ),
    SuggestedJobsItemModel(
      trackLocationImage: Assets.jobGoogleIcon,
      trackLocationTitle: 'Content Marketing',
      trackLocationSubtitle: 'Google | Cairo | Egypt',
      price: '\$42- \$48k',
      subscriptionType: ' /monthly',
      workingTimeSectionTitle1: 'Part_Time',
      workingTimeSectionTitle2: 'Advanced Level',
    ),
    SuggestedJobsItemModel(
      trackLocationImage: Assets.jobGoogleIcon,
      trackLocationTitle: 'Flutter Developer',
      trackLocationSubtitle: 'Google | Cairo | Egypt',
      price: '\$1000- \$1500k',
      subscriptionType: ' /monthly',
      workingTimeSectionTitle1: 'Full_Time',
      workingTimeSectionTitle2: 'Advanced Level',
    ),
    SuggestedJobsItemModel(
      trackLocationImage: Assets.jobGoogleIcon,
      trackLocationTitle: 'Content Marketing',
      trackLocationSubtitle: 'Google | Cairo | Egypt',
      price: '\$42- \$48k',
      subscriptionType: ' /monthly',
      workingTimeSectionTitle1: 'Part_Time',
      workingTimeSectionTitle2: 'Advanced Level',
    ),
    SuggestedJobsItemModel(
      trackLocationImage: Assets.jobGoogleIcon,
      trackLocationTitle: 'Flutter Developer',
      trackLocationSubtitle: 'Google | Cairo | Egypt',
      price: '\$1000- \$1500k',
      subscriptionType: ' /monthly',
      workingTimeSectionTitle1: 'Full_Time',
      workingTimeSectionTitle2: 'Advanced Level',
    ),
    SuggestedJobsItemModel(
      trackLocationImage: Assets.jobGoogleIcon,
      trackLocationTitle: 'Content Marketing',
      trackLocationSubtitle: 'Google | Cairo | Egypt',
      price: '\$42- \$48k',
      subscriptionType: ' /monthly',
      workingTimeSectionTitle1: 'Part_Time',
      workingTimeSectionTitle2: 'Advanced Level',
    ),
    SuggestedJobsItemModel(
      trackLocationImage: Assets.jobGoogleIcon,
      trackLocationTitle: 'Flutter Developer',
      trackLocationSubtitle: 'Google | Cairo | Egypt',
      price: '\$1000- \$1500k',
      subscriptionType: ' /monthly',
      workingTimeSectionTitle1: 'Full_Time',
      workingTimeSectionTitle2: 'Advanced Level',
    ),
    SuggestedJobsItemModel(
      trackLocationImage: Assets.jobGoogleIcon,
      trackLocationTitle: 'Content Marketing',
      trackLocationSubtitle: 'Google | Cairo | Egypt',
      price: '\$42- \$48k',
      subscriptionType: ' /monthly',
      workingTimeSectionTitle1: 'Part_Time',
      workingTimeSectionTitle2: 'Advanced Level',
    ),
    SuggestedJobsItemModel(
      trackLocationImage: Assets.jobGoogleIcon,
      trackLocationTitle: 'Flutter Developer',
      trackLocationSubtitle: 'Google | Cairo | Egypt',
      price: '\$1000- \$1500k',
      subscriptionType: ' /monthly',
      workingTimeSectionTitle1: 'Full_Time',
      workingTimeSectionTitle2: 'Advanced Level',
    ),
  ];
  // Dummy Data
  static const List<RecentJobsCardItemModel> recentJobsItemModelList = [
    RecentJobsCardItemModel(
      title: 'Content Marketing',
      salary: '\$42 - \$48k /month',
      jobType: 'Full-Time',
      company: 'LinkedIn',
      location: 'Remote',
      timeLeft: '30 days left',
    ),
    RecentJobsCardItemModel(
      title: 'UI/UX Designer',
      salary: '\$50 - \$60k /year',
      jobType: 'Part-Time',
      company: 'Google',
      location: 'San Francisco',
      timeLeft: '15 days left',
    ),
    RecentJobsCardItemModel(
      title: 'Content Marketing',
      salary: '\$42 - \$48k /month',
      jobType: 'Full-Time',
      company: 'LinkedIn',
      location: 'Remote',
      timeLeft: '30 days left',
    ),
    RecentJobsCardItemModel(
      title: 'UI/UX Designer',
      salary: '\$50 - \$60k /year',
      jobType: 'Part-Time',
      company: 'Google',
      location: 'San Francisco',
      timeLeft: '15 days left',
    ),
    RecentJobsCardItemModel(
      title: 'Content Marketing',
      salary: '\$42 - \$48k /month',
      jobType: 'Full-Time',
      company: 'LinkedIn',
      location: 'Remote',
      timeLeft: '30 days left',
    ),
    RecentJobsCardItemModel(
      title: 'UI/UX Designer',
      salary: '\$50 - \$60k /year',
      jobType: 'Part-Time',
      company: 'Google',
      location: 'San Francisco',
      timeLeft: '15 days left',
    ),
    RecentJobsCardItemModel(
      title: 'Content Marketing',
      salary: '\$42 - \$48k /month',
      jobType: 'Full-Time',
      company: 'LinkedIn',
      location: 'Remote',
      timeLeft: '30 days left',
    ),
    RecentJobsCardItemModel(
      title: 'UI/UX Designer',
      salary: '\$50 - \$60k /year',
      jobType: 'Part-Time',
      company: 'Google',
      location: 'San Francisco',
      timeLeft: '15 days left',
    ),
    RecentJobsCardItemModel(
      title: 'Content Marketing',
      salary: '\$42 - \$48k /month',
      jobType: 'Full-Time',
      company: 'LinkedIn',
      location: 'Remote',
      timeLeft: '30 days left',
    ),
    RecentJobsCardItemModel(
      title: 'UI/UX Designer',
      salary: '\$50 - \$60k /year',
      jobType: 'Part-Time',
      company: 'Google',
      location: 'San Francisco',
      timeLeft: '15 days left',
    ),
  ];
}
